title: CGS CompCode Club
author:
  name: Alex Maksimov, Year 11 IBDP
  email: alex.maksimov@cgs.act.edu.au

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  CGS Competitive Programming club materials and trainings. Made with ❤️ for Canberra Grammar School.

url: https://cgs-coding-club.github.io

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  skin: dark


# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false

include:
  - /_img
